### ISSUE TITLE
SceneDelegate's "userActivity" callback never invoked

### ISSUE THREAD

**Issue by tifroz** [AppsFlyerSDK/appsflyer-apple-app-clips-sample-app#1]
I made as little changes to the app's config as possible to get it to simply compile and run

-  I changed the `Team` + `Bundle Identifier` under `Signing & Capabilities`
- Removed the "group.fruitapp.appClipMigration" `App Group` config and commented out the related code in `didFinishLaunchingWithOptions` because the "group.fruitapp.appClipMigration" `App Group` does not not exist in my provisioning profile
- Selected the `_XCAppClipURL` argument from the "Fruit AppClip" scheme (with the value left intact i.e. "https://fruits.com/check?fruit_name=bananas")

Running the "Fruit App Clip"  from Xcode, the only SceneDelegate's method that gets called is `func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {...}`.

I would expect `func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {...}` to get called as well but it never does (tried the simulator + device). Any hints as to why this may fail to get called?

**Comment by liaz-af** [comment]
Hi @tifroz ,

For some reason the call to `scene delegate` with `continue` with was broken sometime after _iOS 14 Beta 5_.
I can confirm we see the same unwanted behaviour.
This completely contradicts previous behaviour and Apple's [documentation](https://developer.apple.com/documentation/app_clips/responding_to_invocations).

I'll leave this issue open and continue follow up here. 

Thank you very much for bringing this up and using our demo app.

Liaz

**Comment by tifroz** [comment]
Thanks @liaz-af! I was pulling my hair (I tested with Xcode12 beta6 / iOS 14 beta 8). Hopefully this gets worked out by Apple quickly.

Interestingly, apple's [Fruta Demo App](https://developer.apple.com/documentation/app_clips/fruta_building_a_feature-rich_app_with_swiftui) that uses swiftUI seems to be working ok.

**Comment by liaz-af** [comment]
We have added the following code to handle NSUserActivity in the first invocation of an App Clip.
There was a bit of a misunderstanding in Apple's doc, but I think now we are ok.

Sorry of any inconvenience. Again, thanks for using our demo app.
